# YOLO configuration
YOLO_MODEL_PATH = "yolov8l.pt"
YOLO_CONFIDENCE = 0.6
PERSON_CLASS_ID = 0
FRAME_SAMPLE_INTERVAL = 1

BATCH_SIZE_GPU = 16
BATCH_SIZE_CPU = 4

MULTIPLE_PEOPLE_THRESHOLD = 1
ABSENCE_THRESHOLD = 0